### ISSUE TITLE
show on above the navigation bar

### ISSUE THREAD

**Issue by syrakozz** [ask-fm/AFMInfoBanner#1]
i try it but it show from top above the navigation bar,
how i can make it show under the navigation bar

**Comment by syrakozz** [comment]
in some case the script is fail in finding the navigation bar, can you plz add a hight, for it in that case so the control can act like if there is a navigation bar even if he faild to notice it

**Comment by artworkad** [comment]
:+1: same problem for me

**Comment by vani2** [comment]
Yes, `CVKHierarchySearcher` fail.

**Comment by syrakozz** [comment]
@coverback  plz help

**Comment by karpelcevs** [comment]
Hey! Can you try now, the 1.0.1?
I added a step to search for a `UINavigationBar` in controllers that don't use `UINavigationController`. I'm only searching in `controller.view.subviews`, though, to avoid a recursion.

In general, I'd recommend embedding view controller into a `UINavigationController` even if you don't push anything on top, to take care of the bar instead of adding it yourself.

**Comment by karpelcevs** [comment]
Made another fix, now in `CVKHierarchySearcher` and bumped spec for `AFMInfoBanner` too.
Works for me for different combinations of tab, navigation and usual controllers.

If something is still not working for you, please comment and provide hierarchy for view controllers as well as if the controller has a custom navigation bar.

**Comment by syrakozz** [comment]
its still failng with the latest version

—

**Comment by syrakozz** [comment]
maybe you can grab some idea from this https://github.com/alobi/ALAlertBanner

**Comment by karpelcevs** [comment]
That component uses incompatible approach by specifying the view to attach to. My goal is to show banner without having to specify anything.
Unfortunately I cannot assist you with your issue until there's a test-case.
