### ISSUE TITLE
hide on click

### ISSUE THREAD

**Issue by syrakozz** [ask-fm/AFMInfoBanner#2]
can you plz make it hide on click

**Comment by karpelcevs** [comment]
@syrakozz no. Click would mean opening details of the error, not closing it.

I'd rather make it disappear on swipe like Apple's notifications do, but right now I don't have a need for it. If there'd be a pull request, I'd gladly integrate it.

**Comment by syrakozz** [comment]
or could you plz make a clikkc event for it, so we can control it via block 
so we can catch the click event

**Comment by karpelcevs** [comment]
I won't be adding it as we don't need it. If there's a PR, I'd take a look and probably merge, but I don't see click handling as something that would improve this component for majority of users.

There's a [fork](https://github.com/mdjastrzebski/AFMInfoBanner) that supports hide on click. You can use that one, if you need this functionality.

**Comment by syrakozz** [comment]
ah its already implement on a fork , 
if you can merge it, it will be great, 
and make it as optional offcourse

**Comment by syrakozz** [comment]
if you notice on whatsapp, when you in the favorites screen and the internet wen down, a similar view appear say that there is no internet , in the same view there is a close button on the right, 
im pretty sure that whatsapp add it for a reason,  ( maybe a couple of million suggest )
its great for the UX concept

**Comment by karpelcevs** [comment]
Whatsapp is bad example for UI/UX. The whole idea of this component is to deliver and hide error messages without user interaction.
Given that Apple's own Banner notifications are the most native example of notification UI, I'd follow them instead of Whatsapp. For them slide closes, click opens. I'd gladly integrate a swipe-to-close if someone made a PR for that.

I'm not gonna merge the mentioned fork because it changes API too much. You can use it by specifying a source for a pod:

```
pod 'AFMInfoBanner', :git => 'https://github.com/mdjastrzebski/AFMInfoBanner.git'
```

**Comment by syrakozz** [comment]
thank you
